name: Publish to npm

on:
  release:
    types: [published]
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (leave empty for package.json version)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Run coverage
        run: yarn test:coverage

      - name: Build package
        run: yarn build

      - name: Update version if specified
        if: github.event.inputs.version
        run: |
          yarn version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Publish to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub release notes
        if: github.event_name == 'release'
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });

            console.log(`✅ Published @net7/annotator@${data.tag_name} to npm`);

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: `${data.body || ''}\n\n📦 **Package published to npm**: [@net7/annotator@${data.tag_name}](https://www.npmjs.com/package/@net7/annotator/v/${data.tag_name.replace('v', '')})`
            });
